# Generated by Django 6.0.4 on 2026-04-27 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Escada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20)),
                ('setor_origem', models.CharField(max_length=20)),
                ('data_envio', models.DateField()),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('em_manutencao', 'Em manutenção'), ('concluida', 'Concluída')], default='pedente', max_length=20)),
            ],
        ),
    ]
