# Generated by Django 6.0.4 on 2026-04-28 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manutencao_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='escada',
            name='altura',
            field=models.IntegerField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='escada',
            name='nome',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
