# Generated by Django 6.0.4 on 2026-04-28 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manutencao_app', '0002_escada_altura_escada_nome'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='escada',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='escada',
            name='setor_origem',
        ),
        migrations.AlterField(
            model_name='escada',
            name='altura',
            field=models.IntegerField(default=0),
        ),
    ]
