# Generated by Django 6.0.4 on 2026-04-28 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manutencao_app', '0003_remove_escada_nome_remove_escada_setor_origem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='escada',
            name='problema',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
