# Generated by Django 6.0.4 on 2026-05-04 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manutencao_app', '0004_escada_problema'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='escada',
            name='altura',
        ),
        migrations.AddField(
            model_name='escada',
            name='modelo',
            field=models.CharField(choices=[('escada_es-ca_fort_tesoura_pequena', 'ESCADA ES-CA FORT TESOURA PEQUENA'), ('escada_es-ca_fort_6m_extensiva', 'ESCADA ES-CA FORT 6M EXTENSIVA')], default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='escada',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('em_manutencao', 'Em manutenção'), ('concluida', 'Concluída')], default='pendente', max_length=20),
        ),
    ]
